package msmengine

import (
	"math/big"
	"testing"

	"github.com/consensys/gnark-crypto/ecc"
	bls12381 "github.com/consensys/gnark-crypto/ecc/bls12-381"
	"github.com/consensys/gnark-crypto/ecc/bls12-381/fr"
)

// randomG1Vec returns n random G1Affine points and n random fr.Element scalars.
// Points are generated by scalar-multiplying the BLS12-381 G1 generator by
// independent random field elements, so they are guaranteed to be on the curve.
func randomG1Vec(t *testing.T, n int) ([]bls12381.G1Affine, []fr.Element) {
	t.Helper()
	pts := make([]bls12381.G1Affine, n)
	scs := make([]fr.Element, n)
	for i := range pts {
		var ptSc fr.Element
		if _, err := ptSc.SetRandom(); err != nil {
			t.Fatalf("randomG1Vec: SetRandom point scalar: %v", err)
		}
		var bigPtSc big.Int
		ptSc.BigInt(&bigPtSc)
		var jac bls12381.G1Jac
		jac.ScalarMultiplicationBase(&bigPtSc)
		pts[i].FromJacobian(&jac)

		if _, err := scs[i].SetRandom(); err != nil {
			t.Fatalf("randomG1Vec: SetRandom scalar: %v", err)
		}
	}
	return pts, scs
}

// TestCPUEngineMatchesDirectMultiExp verifies that cpuMSM.MSMG1 produces
// exactly the same result as calling dst.MultiExp directly with NbTasks:1.
func TestCPUEngineMatchesDirectMultiExp(t *testing.T) {
	pts, scs := randomG1Vec(t, 4096)

	var want bls12381.G1Jac
	if _, err := want.MultiExp(pts, scs, ecc.MultiExpConfig{NbTasks: 1}); err != nil {
		t.Fatal(err)
	}

	var got bls12381.G1Jac
	if err := (cpuMSM{}).MSMG1(&got, pts, scs, nil); err != nil {
		t.Fatal(err)
	}

	if !got.Equal(&want) {
		t.Fatal("cpuMSM G1 != direct MultiExp")
	}
}

// TestCPUEngineG2MatchesDirectMultiExp verifies that cpuMSM.MSMG2 produces
// the same result as direct G2Jac.MultiExp with NbTasks:1.
func TestCPUEngineG2MatchesDirectMultiExp(t *testing.T) {
	n := 512
	pts := make([]bls12381.G2Affine, n)
	scs := make([]fr.Element, n)

	_, g2Gen, _, _ := bls12381.Generators()
	for i := range pts {
		var ptSc fr.Element
		if _, err := ptSc.SetRandom(); err != nil {
			t.Fatalf("SetRandom point scalar: %v", err)
		}
		var bigPtSc big.Int
		ptSc.BigInt(&bigPtSc)
		var jac bls12381.G2Jac
		jac.ScalarMultiplication(&g2Gen, &bigPtSc)
		pts[i].FromJacobian(&jac)

		if _, err := scs[i].SetRandom(); err != nil {
			t.Fatalf("SetRandom scalar: %v", err)
		}
	}

	var want bls12381.G2Jac
	if _, err := want.MultiExp(pts, scs, ecc.MultiExpConfig{NbTasks: 1}); err != nil {
		t.Fatal(err)
	}

	var got bls12381.G2Jac
	if err := (cpuMSM{}).MSMG2(&got, pts, scs, nil); err != nil {
		t.Fatal(err)
	}

	if !got.Equal(&want) {
		t.Fatal("cpuMSM G2 != direct MultiExp")
	}
}

// TestProgressFnFired verifies that the ProgressFn callback is invoked when
// non-nil, with done == total == len(scalars).
func TestProgressFnFired(t *testing.T) {
	pts, scs := randomG1Vec(t, 64)

	called := false
	var doneSeen, totalSeen int
	prog := func(done, total int) {
		called = true
		doneSeen = done
		totalSeen = total
	}

	var dst bls12381.G1Jac
	if err := (cpuMSM{}).MSMG1(&dst, pts, scs, prog); err != nil {
		t.Fatal(err)
	}
	if !called {
		t.Fatal("ProgressFn was not called")
	}
	if doneSeen != len(scs) || totalSeen != len(scs) {
		t.Fatalf("ProgressFn got done=%d total=%d, want %d/%d", doneSeen, totalSeen, len(scs), len(scs))
	}
}

// TestCurrentDefaultIsCPU verifies the global default engine is cpuMSM.
func TestCurrentDefaultIsCPU(t *testing.T) {
	if Current().Name() != "cpu" {
		t.Fatalf("default engine name = %q, want %q", Current().Name(), "cpu")
	}
}

// stubMSM is a minimal MSMEngine used only in tests to produce a Name()
// distinct from cpuMSM so that TestSetCurrent can observe a real swap.
// It delegates all math to cpuMSM so correctness is still verified.
type stubMSM struct{}

func (stubMSM) Name() string { return "stub" }
func (stubMSM) MSMG1(dst *bls12381.G1Jac, points []bls12381.G1Affine, scalars []fr.Element, prog ProgressFn) error {
	return (cpuMSM{}).MSMG1(dst, points, scalars, prog)
}
func (stubMSM) MSMG2(dst *bls12381.G2Jac, points []bls12381.G2Affine, scalars []fr.Element, prog ProgressFn) error {
	return (cpuMSM{}).MSMG2(dst, points, scalars, prog)
}
func (stubMSM) MSMG1Ranged(dst *bls12381.G1Jac, n int, fetch FetchG1, scalars []fr.Element, prog ProgressFn) error {
	return (cpuMSM{}).MSMG1Ranged(dst, n, fetch, scalars, prog)
}
func (stubMSM) MSMG2Ranged(dst *bls12381.G2Jac, n int, fetch FetchG2, scalars []fr.Element, prog ProgressFn) error {
	return (cpuMSM{}).MSMG2Ranged(dst, n, fetch, scalars, prog)
}
func (stubMSM) Close() error { return nil }

// TestSetCurrent verifies SetCurrent swaps the global engine to a
// distinguishable value and Current() returns the new one.
func TestSetCurrent(t *testing.T) {
	orig := Current()
	t.Cleanup(func() { SetCurrent(orig) })

	SetCurrent(stubMSM{})
	if Current().Name() != "stub" {
		t.Fatalf("after SetCurrent(stubMSM{}) Name = %q, want stub", Current().Name())
	}
}
